# Uncomment this line to define a global platform for your project
platform :ios, '9.2'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ejercicioTwitter' do

pod 'DateTools'

end

target 'ejercicioTwitterTests' do

end

target 'ejercicioTwitterUITests' do

end

